### ISSUE TITLE
技术写作项目申领

### ISSUE THREAD

**Issue by xulihang** [PKUCATers/forum#1]
三个小组：
- Sphinx快速入门（安装、写内容、发布等）
- Github快速入门（github作用，基本操作，githubpages等）
- Restructured快速入门（基本语法，写作工具，预览等）

**Comment by xulihang** [comment]
## GitHub:

@puleiying
@Wontaigne 
@flycrane01 
@violet-li 
@pkucat
@Susansama 
@Funster-X 

## Sphinx:

@Cpssea 
@WeiYi95 
@yirongzheng 
@Gavinson 
@buzhidaoqishenme 
@xueji0125

## rst:

@sibylxu 
@nicholezyn 
@ssz1984 
@xulihang
@CPCer
@jennacheung 
@daxiaooooo

**Comment by yirongzheng** [comment]
Sphinx

**Comment by flycrane01** [comment]
GitHub

**Comment by xulihang** [comment]
@galty687 小组成员报齐了
